### ISSUE TITLE
Supporting both timeline and blog posts

### ISSUE THREAD

**Issue by le4ker** [kirbyt/timeline-jekyll-theme#1]
Hello,

Thanks for the theme, it's really simple and beautiful.

But I think that it would be even greater if you could support both timeline updates and posts. 
i.e. blog posts would go under _posts and timeline under _timeline.

I am willing to contribute on that (if you decide that it make sense as a feature). Do you have any pointers of how to integrate this change?

Thanks!
:panos

**Comment by kirbyt** [comment]
I'm not sure how to go about this. You can just have an index page, or a timeline page that gets included, and let Jekyll do it's normal blog posting thing. I opted against this because I didn't need a blog for the site I was working on, and I wanted a way to update the timeline just like I would update a blog site with a new post. 

If I also needed a blog, then I would just hand code the timeline HTML and use the posts for the blog instead of generating the timeline from the post.

**Comment by le4ker** [comment]
After I found that jekyll cannot distinguish different post categories, I had the same idea. 
Given that the frequency of the timeline additions is too small compared to the blog posts, it makes sense to strip the html and include it and then let jekyll handle the blog posts.

Thanks!
